name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
   # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          # gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
         # gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          #distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare Maven environnement with Java 17 for deployment to Sonatype
        run: export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"

     # - name: Customize the Maven settings.xml
      #  uses: whelk-io/maven-settings-xml-action@7c60eb95b2d5ec18f2e0e29f34c9ed69475e7a96 # v21
       # with:
        #  servers: '[{ "id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }]'

      - name: Deploy with Maven
        run: mvn deploy -PsonatypeDeploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         # run: |
          #mvn clean deploy -PsonatypeDeploy -B -U -ntp -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
